### ISSUE TITLE
Calculation of issue comment is wrong

### ISSUE THREAD

**Issue by Swechhya** [Lf-Network/oss-leaderboard#28]
For `issue comments` the points calculated are wrong.
While calculating the `issue comments` the total points counted are not for the particular user but for all the user comments in that issue. 

Check for user's id has to be added while calculating the `issue comments`.

**Comment by aanchal-adk** [comment]
I'll work on this

**Comment by kabirbaidhya** [comment]
@aanchal-adk Was this issue fixed with #29?

**Comment by mesaugat** [comment]
Might have been solve. Closing because issue is stale.
