### ISSUE TITLE
Add Navbar in Leaderboard

### ISSUE THREAD

**Issue by RikLakhe** [Lf-Network/oss-leaderboard#46]
Task,
1. Add navbar in Leaderboard

![image](https://github.com/Lf-Network/oss-leaderboard/assets/25451595/6f7db07e-45ce-4b65-bc9e-b2e8ee25d45a)

**Comment by SpandanNepal** [comment]
[PR](https://github.com/Lf-Network/oss-leaderboard/pull/57) is ready for review.
