### ISSUE TITLE
Make Leaderboard row clickable

### ISSUE THREAD

**Issue by RikLakhe** [Lf-Network/oss-leaderboard#47]
Task
1. Make each row of Leaderboard clickable
2. Upon clicking the row should redirect to GitHub user's profile 

![image](https://github.com/Lf-Network/oss-leaderboard/assets/25451595/5e1f5df1-67e4-4c46-80ac-edb1362edcf6)

**Comment by mesaugat** [comment]
Let's also add user's GitHub profile picture before the name.

**Comment by shresthalucky** [comment]
@RikLakhe  I'm unsure about row, but here is a PR https://github.com/Lf-Network/oss-leaderboard/pull/55 for making the username clickable. Please review the PR. Thanks.

@mesaugat I will create next PR to get user profile picture.

**Comment by shresthalucky** [comment]
@mesaugat Added user avatar. Please review the PR https://github.com/Lf-Network/oss-leaderboard/pull/58.
