### ISSUE TITLE
Improve Error Handling for Invalid Usernames in Leaderboard Calculation

### ISSUE THREAD

**Issue by Swechhya** [Lf-Network/oss-leaderboard#49]
## Description:

Currently, when processing the `USER_LIST`  for leaderboard score computation, if an invalid GitHub username is encountered, the application crashes, disrupting the entire process. To enhance the robustness of the app, we need to implement proper error handling. Specifically, when an invalid username is detected, it should be ignored, and the leaderboard scores should still be calculated for the remaining valid usernames.

### Steps to Reproduce:

1. Provide a USER_LIST with one or more invalid GitHub usernames.
2. Run the application to compute the leaderboard scores.

#### Current Behavior:

The application fails with an error message when encountering an invalid username in the `USER_LIST`, preventing leaderboard score computation.

#### Expected Behavior:

- When an invalid GitHub username is detected in the USER_LIST, the application should log an error message.
- The invalid username should be ignored.
- The application should continue processing the remaining valid usernames in the USER_LIST to calculate leaderboard scores.
- Upon completion, the application should display the leaderboard with scores for valid usernames only.

**Comment by SpandanNepal** [comment]
[PR](https://github.com/Lf-Network/oss-leaderboard/pull/54) is ready for review.
