### ISSUE TITLE
Add GitHub Ribbon

### ISSUE THREAD

**Issue by shresthalucky** [Lf-Network/oss-leaderboard#59]
Thinking of adding a **Fork me on GitHub** ribbon. Any thoughts?

![image](https://github.com/Lf-Network/oss-leaderboard/assets/4192121/9fa6325b-6351-4551-8b08-9f425bf7f301)

ref: https://github.blog/2008-12-19-github-ribbons/

cc @mesaugat @Swechhya @RikLakhe

**Comment by mesaugat** [comment]
Maybe just add a footer with a link to GitHub.

Ribbons are too old school.

**Comment by shresthalucky** [comment]
> Maybe just add a footer with a link to GitHub.
> 
> Ribbons are too old school.

True :rofl: 
Maybe a github icon in nav bar. Similar to https://react.dev/

**Comment by mesaugat** [comment]
@shresthalucky Yes, that sounds better.

**Comment by mesaugat** [comment]
@shresthalucky Yes, that sounds better.

**Comment by mesaugat** [comment]
@shresthalucky Yes, that sounds better.

**Comment by shresthalucky** [comment]
@mesaugat Please review the PR https://github.com/Lf-Network/oss-leaderboard/pull/60. Thanks.
