### ISSUE TITLE
Fix Case Sensitivity in Username Matching for Accurate Leaderboard Rendering

### ISSUE THREAD

**Issue by JeevaRamanathan** [Lf-Network/oss-leaderboard#73]
GitHub usernames are case-insensitive but case-preserving, meaning usernames can be entered in any case, but GitHub will always return the original capitalization chosen by the user at the time of account creation. In the current leaderboard code, the GraphQL query retrieves usernames with their proper capitalization, which may differ from the usernames provided in the user_list (participants) if they are in a different case. As a result, users whose usernames have different capitalization in the list is not rendered in the result table when the userlist in provided in `.env` file.

I would like to work on this issue in this approach, reading the user list [here](https://github.com/Lf-Network/oss-leaderboard/blob/ff975dfeebbc3f47cd049c9bc32e6b3a782d20e6/main.py#L13) in lower case and changing all the instances of user_name into lowercase in [formatter file](https://github.com/Lf-Network/oss-leaderboard/blob/ff975dfeebbc3f47cd049c9bc32e6b3a782d20e6/leaderboard/utils/formatter.py#L191).
Currently [Intermediate Score Table](https://github.com/Lf-Network/oss-leaderboard/blob/ff975dfeebbc3f47cd049c9bc32e6b3a782d20e6/main.py#L36) retrieves the value but failed to identify in [Final Score Table](https://github.com/Lf-Network/oss-leaderboard/blob/ff975dfeebbc3f47cd049c9bc32e6b3a782d20e6/leaderboard/utils/final_score_table.py#L44).

Eg., user_list with JeevaRamanathan will render the data in table and jeevramanathan will fail at final_score_table function although the data is retrieved.

@Swechhya, @RikLakhe or team your input on this is highly appreciated before raising a PR if I can follow the above method

**Comment by ShoomanKhatri** [comment]
JeevaRamanathan  bro

I’m facing the same issue — my name"shoomankhatri"  is also not rendering on the leaderboard due to the case sensitivity in the username matching. Even though my data is retrieved, the difference in capitalization between the user list and the query result causes it to not appear in the final score table.

**Comment by Swechhya** [comment]
@JeevaRamanathan , you're welcome to take on this issue. My suggestion is as follows:
- Perform the comparison in lowercase to ensure consistency.
- However, when displaying the final score table, retain the original capitalization for user names to preserve the correct formatting.

Let me know if you have any questions or need further clarification.

**Comment by JeevaRamanathan** [comment]
@ShoomanKhatri now you will be able to see :)
